spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: none



  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/practice?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
  mail:
    address:
      admin: admin@gmail.com
  jwt:
    key: ${JWT_SECRET_KEY}
    access-token-expiration-minutes: 40
    refresh-token-expiration-minutes: 420
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${G_CLIENT_ID}
            clientSecret: ${G_CLIENT_SECRET}
            scope:
              - email
              - profile
